### ISSUE TITLE
AWS WAF Captcha support?

### ISSUE THREAD

**Issue by pahud** [iKala-Cloud/aws-waf-solution#26]
Are we able to add this support into this construct?

https://docs.aws.amazon.com/waf/latest/developerguide/waf-captcha.html
https://dev.classmethod.jp/articles/aws-waf-captcha-support/

**Comment by kimisme9386** [comment]
It looks like a great feature! I will figure out the mechanism of Captcha and consider support it. 
Thanks for your suggestion.  @pahud
